# 开发环境配置
app:
  host: "0.0.0.0"
  port: 7789
  jwtSecreKey: "appMaker"
  jwtExpireTime: "15h"

  
# ng配置
ngSettings: 
  host: "http://172.16.0.112:30106"
  ngAPiEncryptionKey: "1oHtvRD0uA6NwSDL3/+FOZPnwkF3GsCtFnxifc8v/Tk="

# vprofile配置
vProfileSettings:
  host: "http://172.16.0.112:30056"
  apiAccess: "SG1Fc0lHVWY0Zno5ZVFwQUU5dEJDL3phRmhzelExRmtuWDQ2SjZ1RmtMbDJxc2FUQ1laa0RBPT0="
  apis: {
    registerUser: "/api/master/RegisterUser",
    getApplicationRoles: "/api/master/getApplicationRoles",
    verify: "/api/master/Verify",
    getApplicationByCode: "/api/master/GetApplicationByCode",
  }
